const MIN_ORDER_QUANTITY = 1;
const MAX_ORDER_QUANTITY = 9;
const RANKING_RANGE = 3;
const PRIMARY_RANK_RANGE = 1;
const SECONDARY_RANK_RANGE = 2;
const TERTIARY_RANK_RANKGE = 3;
const PAYMENT_METHOD_NAMES = {
  CARD: '카드',
  CASH: '현금',
};
const BILL_DISPLAYING_TIME = 7;
const AVAILABLE_CASH = [50000, 10000, 5000, 1000, 500, 100];
const policy = {
  MIN_ORDER_QUANTITY,
  MAX_ORDER_QUANTITY,
  RANKING_RANGE,
  PRIMARY_RANK_RANGE,
  SECONDARY_RANK_RANGE,
  TERTIARY_RANK_RANKGE,
  PAYMENT_METHOD_NAMES,
  BILL_DISPLAYING_TIME,
  AVAILABLE_CASH,
};

export default policy;
